### ISSUE TITLE
Player collision detecting collisions where it shouldn't

### ISSUE THREAD

**Issue by bonnielunawalker** [SDP-Project/ButlerMan#1]
Seems to be a bug with player collisions. In the following screenshot, I was not able to move to the left despite there being a gap that I could logically travel through.

![capture](https://cloud.githubusercontent.com/assets/11156703/19583572/9b8009f4-9789-11e6-9bea-275ef80241d3.PNG)

**Comment by Plottel** [comment]
I think this is because of something I changed to accommodate Unit Tests - will have a look.

**Comment by Plottel** [comment]
Resolved.
Was caused by Player movement being greater than 1. Player is the same size as Tile, so needs pixel perfect positioning to fit. When moving >1 pixel per frame, he detects a collision in advance and will never  get into correct position.
Fixed by allowing Player to move pixel by pixel if a collision is detected in advance.
